// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aczrgkcpgmfcjkujrnlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjenJna2NwZ21mY2prdWpybmx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjYxOTUsImV4cCI6MjA2MzI0MjE5NX0.seMcC2iQv7cP6xt2oZIPUqac1-HNPq9jy5PXJsbzTYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);