// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dholnpzezdftsxgppugz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRob2xucHplemRmdHN4Z3BwdWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTExMzYsImV4cCI6MjA2MjQ2NzEzNn0.N0QSAWe9lZUiw1kwzBzMkvYXnta2oaahUD8yfXkL948";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);